#pragma once

#include_next <pebble_process_info.h>

#ifdef PEBBLEBOY_CFW_OFFICIAL_SDK_BRIDGE
#undef PROCESS_INFO_CURRENT_SDK_VERSION_MAJOR
#undef PROCESS_INFO_CURRENT_SDK_VERSION_MINOR
#define PROCESS_INFO_CURRENT_SDK_VERSION_MAJOR 0x5
#define PROCESS_INFO_CURRENT_SDK_VERSION_MINOR 0x6b
#endif
